# Generated by Django 6.0.3 on 2026-06-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0001_initial'),
    ]

    operations = []
