# Generated by Django 6.0.3 on 2026-05-07 08:47

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[products.validators.positive_validator])),
                ('quantity', models.IntegerField(validators=[products.validators.positive_validator])),
            ],
        ),
    ]
